/* eslint-disable */
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const { FieldValue } = require('firebase-admin/firestore');
const { getFeaturesForPlan } = require('../Helpers/subscriptionHelper');

if (!admin.apps.length) {
  admin.initializeApp();
}

const db = admin.firestore();

/**
 * Scheduled Cloud Function running daily to check for expired trials
 * Runs at 00:00 UTC-5 (America/Lima)
 */
module.exports = functions
  .runWith({
    timeoutSeconds: 300,
    memory: '256MB'
  })
  .pubsub
  .schedule('0 0 * * *')
  .timeZone('America/Lima')
  .onRun(async (context) => {
    const startTime = Date.now();
    const now = new Date();

    console.log('🤖 ========================================');
    console.log('🤖 TRIAL EXPIRATION CHECKER START');
    console.log('🤖 ========================================');
    console.log(`🕐 Execution time: ${now.toISOString()}`);

    try {
      // Query businesses where subscription.status is 'trial'
      // Note: We'll fetch all trials and filter expired ones in JS to avoid complex Firestore indexing if endDate filter requires composite index
      const trialsSnapshot = await db.collection('businesses')
        .where('subscription.status', '==', 'trial')
        .get();

      console.log(`📊 Found ${trialsSnapshot.size} active trials to check.`);

      let expiredCount = 0;
      const batch = db.batch();

      for (const businessDoc of trialsSnapshot.docs) {
        const businessData = businessDoc.data();
        const sub = businessData.subscription || {};

        if (!sub.endDate) continue;

        // Convert Firestore Timestamp to JS Date
        const endDate = sub.endDate.toDate();

        if (now >= endDate) {
          const businessId = businessDoc.id;
          console.log(`⚠️ Business ${businessId} ("${businessData.nombre || businessData.businessName}") trial has expired.`);

          const freeFeatures = getFeaturesForPlan('free');
          
          const subscriptionUpdate = {
            'subscription.plan': 'free',
            'subscription.status': 'active',
            'subscription.updatedAt': FieldValue.serverTimestamp(),
            'subscription.updatedBy': 'system_scheduler',
            features: freeFeatures
          };

          const businessRef = db.collection('businesses').doc(businessId);
          batch.update(businessRef, subscriptionUpdate);

          // Add a subscription history entry
          const historyRef = db.collection(`businesses/${businessId}/subscriptions`).doc();
          batch.set(historyRef, {
            plan: 'free',
            status: 'active',
            startDate: FieldValue.serverTimestamp(),
            endDate: null,
            trialSource: 'profile_completion',
            type: 'trial_expiration',
            createdAt: FieldValue.serverTimestamp(),
            notes: 'Prueba gratuita expirada - Cambio automático a Free'
          });

          // Add traceability log
          const traceRef = db.collection(`businesses/${businessId}/traceability_logs`).doc();
          batch.set(traceRef, {
            operationType: 'subscription_expire',
            entityType: 'business',
            entityId: businessId,
            operation: 'trial_expired',
            triggerType: 'scheduled_trial_expiration',
            autoGenerated: true,
            executedAt: FieldValue.serverTimestamp(),
            timestamp: FieldValue.serverTimestamp()
          });

          expiredCount++;
        }
      }

      if (expiredCount > 0) {
        await batch.commit();
        console.log(`✅ Successfully downgraded ${expiredCount} expired trials to free plan.`);
      } else {
        console.log('✓ No expired trials found today.');
      }

      const duration = Date.now() - startTime;
      console.log('🤖 ========================================');
      console.log(`⏱️ Duration: ${duration}ms`);
      console.log('🤖 TRIAL EXPIRATION CHECKER COMPLETED');
      console.log('🤖 ========================================');

      // Save execution summary
      await db.collection('scheduledExecutions').add({
        type: 'trial_expiration',
        version: '1.0',
        results: {
          checked: trialsSnapshot.size,
          expired: expiredCount
        },
        duration,
        executedAt: FieldValue.serverTimestamp(),
        success: true
      });

      return null;
    } catch (error) {
      console.error('❌ Error checking trial expirations:', error);
      
      await db.collection('scheduledExecutions').add({
        type: 'trial_expiration',
        version: '1.0',
        error: error.message,
        stack: error.stack,
        executedAt: FieldValue.serverTimestamp(),
        success: false
      });
      
      throw error;
    }
  });
