/* eslint-disable */
// autoOpening.js

/**
 * @file autoOpening.js
 * @description Función que genera automáticamente una apertura de caja cuando no existe.
 * Se basa en el último cierre registrado para cargar los saldos iniciales.
 * 
 * Esta función es llamada por scheduledAutoClose.js ANTES de procesar el cierre automático,
 * asegurando que siempre haya una apertura disponible para calcular los agregados.
 * 
 * Infraestructura consistente con:
 * - scheduledAutoClose.js (cierre automático programado - integración completa)
 * - useTransaction.js (creación de transacciones)
 * - transactionStore.js (estructura de datos)
 * - useCashClosure.js (lógica de cierre)
 * - accountsBalanceStore.js (cálculos financieros)
 * 
 * Flujo de ejecución:
 * 1. Verificar que NO exista apertura para el día especificado
 * 2. Buscar el cierre más reciente (normalmente del día anterior)
 * 3. Copiar los saldos finales del cierre como saldos iniciales
 * 4. Crear transacción tipo 'opening' con fuente 'copilot'
 * 5. Actualizar resumen diario con la apertura automática
 * 6. Retornar resultado para que scheduledAutoClose continúe con el cierre
 * 
 * @module AccountsBalance/autoOpening
 */

const functions = require('firebase-functions');
const admin = require('firebase-admin');
const { FieldValue } = require('firebase-admin/firestore');
const { v4: uuidv4 } = require('uuid');

// Inicializar Firebase Admin si no está inicializado
if (!admin.apps.length) {
  admin.initializeApp();
}

const db = admin.firestore();

const { dateRangeForDay } = require('../Helpers/time');
const { getDayAggregates, upsertDailySummary } = require('./sharedComputed');

const DEFAULT_TZ = 'America/Lima';

/**
 * Busca el cierre más reciente antes del día especificado.
 * 
 * @param {FirebaseFirestore.Firestore} db - Instancia de Firestore
 * @param {string} businessId - ID del negocio
 * @param {Date} beforeDate - Fecha límite (buscar antes de esta fecha)
 * 
 * @returns {Promise<Object|null>} Datos del último cierre o null si no existe
 * 
 * Estructura retornada:
 * {
 *   id: string,
 *   realCashBalance: number,
 *   realBankBalance: number,
 *   totalCash: number,
 *   totalBank: number,
 *   expectedCashBalance: number,
 *   expectedBankBalance: number,
 *   createdAt: Timestamp,
 *   day: string,
 *   ...resto de campos del closure
 * }
 */
async function findMostRecentClosure(db, businessId, beforeDate) {
  console.log(`🔍 Searching for most recent closure before ${beforeDate.toISOString()}`);

  const closureSnap = await db.collection(`businesses/${businessId}/transactions`)
    .where('type', '==', 'closure')
    .where('createdAt', '<', beforeDate)
    .orderBy('createdAt', 'desc')
    .limit(1)
    .get();

  if (closureSnap.empty) {
    console.log(`❌ No previous closure found`);
    return null;
  }

  const closureDoc = closureSnap.docs[0];
  const closureData = { id: closureDoc.id, ...closureDoc.data() };

  console.log(`✅ Found closure: ${closureData.id}`);
  console.log(`   📅 Created at: ${closureData.createdAt?.toDate()?.toISOString() || 'N/A'}`);
  console.log(`   💰 Real Cash: ${closureData.realCashBalance || closureData.totalCash || 0}`);
  console.log(`   🏦 Real Bank: ${closureData.realBankBalance || closureData.totalBank || 0}`);

  return closureData;
}

/**
 * Crea una transacción de apertura automática basada en el último cierre.
 * 
 * @param {FirebaseFirestore.Firestore} db - Instancia de Firestore
 * @param {string} businessId - ID del negocio
 * @param {string} day - Día para el cual crear la apertura ('yyyy-LL-dd')
 * @param {Object} lastClosure - Datos del último cierre
 * @param {string} tz - Timezone
 * 
 * @returns {Promise<string>} UUID de la transacción de apertura creada
 * 
 * Estructura de la transacción de apertura (consistente con useTransaction.js):
 * {
 *   uuid: string,
 *   type: 'opening',
 *   description: 'Apertura automática',
 *   source: 'copilot',
 *   copilotMode: 'auto_opening',
 *   
 *   // Saldos iniciales (copiados del cierre anterior)
 *   realCashBalance: number,
 *   realBankBalance: number,
 *   totalCash: number,
 *   totalBank: number,
 *   
 *   // Referencia al cierre del que se tomaron los datos
 *   previousClosureReference: string,
 *   
 *   // Metadata para trazabilidad
 *   metadata: {
 *     day: string,
 *     triggerType: 'auto_opening',
 *     autoGenerated: true,
 *     executionTime: string,
 *     previousClosureId: string,
 *     previousClosureDate: string
 *   },
 *   
 *   createdAt: Timestamp
 * }
 */
async function createAutoOpening(db, businessId, day, lastClosure, tz = DEFAULT_TZ) {
  console.log(`\n🚀 Creating automatic opening for ${day}`);

  // Generar UUID para la transacción (consistente con useTransaction)
  const openingUuid = uuidv4();
  const openingRef = db.collection(`businesses/${businessId}/transactions`).doc(openingUuid);

  // Extraer saldos finales del último cierre
  // Priorizar realCashBalance/realBankBalance, luego totalCash/totalBank
  const cashBalance = lastClosure.realCashBalance ?? lastClosure.totalCash ?? 0;
  const bankBalance = lastClosure.realBankBalance ?? lastClosure.totalBank ?? 0;

  console.log(`💰 Initial balances from last closure:`);
  console.log(`   Cash: ${cashBalance}`);
  console.log(`   Bank: ${bankBalance}`);
  console.log(`   Total: ${cashBalance + bankBalance}`);

  // Estructura completa de apertura automática
  const openingTransaction = {
    uuid: openingUuid,
    type: 'opening',
    description: 'Apertura automática generada por el sistema',
    source: 'copilot',
    copilotMode: 'auto_opening',

    // Saldos iniciales (copiados del cierre anterior)
    realCashBalance: cashBalance,
    realBankBalance: bankBalance,
    totalCash: cashBalance,
    totalBank: bankBalance,

    // Campos compatibles con diferentes versiones del sistema
    cashAmount: cashBalance,
    bankAmount: bankBalance,
    amount: 0, // Apertura no tiene monto de transacción

    items: [],
    itemsAndStockLogs: [],

    // Referencia al cierre del que se tomaron los datos
    previousClosureReference: lastClosure.id,

    // Metadata para trazabilidad
    metadata: {
      day: day,
      triggerType: 'auto_opening',
      autoGenerated: true,
      executionTime: new Date().toISOString(),
      previousClosureId: lastClosure.id,
      previousClosureDate: lastClosure.createdAt?.toDate()?.toISOString() || 'N/A',
      timezone: tz
    },

    createdAt: FieldValue.serverTimestamp()
  };

  // Crear transacción de apertura
  await openingRef.set(openingTransaction);
  console.log(`✅ Opening created: ${openingUuid}`);

  // Registrar en traceability_logs para trazabilidad completa
  await db.collection(`businesses/${businessId}/traceability_logs`).add({
    operationType: 'auto_opening',
    entityType: 'transaction',
    entityId: openingUuid,
    operation: 'automatic_opening',
    day,
    openingTransactionId: openingUuid,
    previousClosureId: lastClosure.id,
    triggerType: 'auto_opening',
    autoGenerated: true,
    financialData: {
      initialCashBalance: cashBalance,
      initialBankBalance: bankBalance,
      totalInitialBalance: cashBalance + bankBalance
    },
    executedAt: FieldValue.serverTimestamp(),
    timestamp: FieldValue.serverTimestamp()
  });

  console.log(`📝 Traceability log created`);

  return openingUuid;
}

/**
 * Función principal de apertura automática.
 * Puede ser llamada desde otras Cloud Functions o endpoints HTTP.
 * 
 * @param {Object} params - Parámetros de la función
 * @param {string} params.businessId - ID del negocio
 * @param {string} params.day - Día para crear apertura ('yyyy-LL-dd')
 * @param {string} [params.timezone] - Timezone (default: 'America/Lima')
 * 
 * @returns {Promise<Object>} Resultado de la operación
 * {
 *   success: boolean,
 *   openingId: string | null,
 *   message: string,
 *   data: {
 *     day: string,
 *     businessId: string,
 *     openingId: string,
 *     previousClosureId: string,
 *     initialCashBalance: number,
 *     initialBankBalance: number
 *   }
 * }
 */
async function executeAutoOpening(params) {
  const { businessId, day, timezone = DEFAULT_TZ } = params;

  console.log(`\n${'='.repeat(60)}`);
  console.log(`🤖 AUTO OPENING EXECUTION START`);
  console.log(`${'='.repeat(60)}`);
  console.log(`🏪 Business ID: ${businessId}`);
  console.log(`📅 Day: ${day}`);
  console.log(`🌍 Timezone: ${timezone}`);
  console.log(`🕐 Execution time: ${new Date().toISOString()}`);

  try {
    // === PASO 1: Verificar que NO exista apertura ===
    console.log(`\n📋 STEP 1: Checking if opening already exists...`);

    const { start, end } = dateRangeForDay(day, timezone);

    const existingOpeningSnap = await db.collection(`businesses/${businessId}/transactions`)
      .where('type', '==', 'opening')
      .where('createdAt', '>=', start)
      .where('createdAt', '<=', end)
      .limit(1)
      .get();

    if (!existingOpeningSnap.empty) {
      const existingOpening = existingOpeningSnap.docs[0];
      console.log(`⚠️  Opening already exists: ${existingOpening.id}`);
      console.log(`   Skipping auto-opening creation`);

      return {
        success: false,
        openingId: existingOpening.id,
        message: `Opening already exists for ${day}`,
        data: {
          day,
          businessId,
          openingId: existingOpening.id,
          alreadyExists: true
        }
      };
    }

    console.log(`✅ No opening found - proceeding with auto-opening`);

    // === PASO 2: Buscar el cierre más reciente ===
    console.log(`\n📋 STEP 2: Finding most recent closure...`);

    const lastClosure = await findMostRecentClosure(db, businessId, start);

    if (!lastClosure) {
      console.log(`❌ No previous closure found - cannot create auto-opening`);

      return {
        success: false,
        openingId: null,
        message: `No previous closure found for business ${businessId}`,
        data: {
          day,
          businessId,
          noPreviousClosure: true
        }
      };
    }

    console.log(`✅ Previous closure found: ${lastClosure.id}`);

    // === PASO 3: Crear apertura automática ===
    console.log(`\n📋 STEP 3: Creating automatic opening...`);

    const openingId = await createAutoOpening(db, businessId, day, lastClosure, timezone);

    console.log(`✅ Auto-opening created successfully: ${openingId}`);

    // === PASO 4: Recalcular agregados del día ===
    console.log(`\n📋 STEP 4: Recalculating day aggregates...`);

    const aggregates = await getDayAggregates(db, businessId, day, timezone);

    console.log(`✅ Aggregates calculated:`, {
      hasOpening: aggregates.hasOpening,
      hasClosure: aggregates.hasClosure,
      hasTxn: aggregates.hasTxn
    });

    // === PASO 5: Actualizar resumen diario ===
    console.log(`\n📋 STEP 5: Updating daily summary...`);

    await upsertDailySummary(db, businessId, day, {
      ...aggregates,
      isAutoOpened: true,
      openingId: openingId,
      autoOpenReason: 'auto_opening',
      autoOpenedAt: FieldValue.serverTimestamp()
    });

    console.log(`✅ Daily summary updated`);

    // === RESULTADO FINAL ===
    const result = {
      success: true,
      openingId: openingId,
      message: `Auto-opening created successfully for ${day}`,
      data: {
        day,
        businessId,
        openingId,
        previousClosureId: lastClosure.id,
        initialCashBalance: lastClosure.realCashBalance ?? lastClosure.totalCash ?? 0,
        initialBankBalance: lastClosure.realBankBalance ?? lastClosure.totalBank ?? 0,
        timezone
      }
    };

    console.log(`\n✅ AUTO OPENING COMPLETED SUCCESSFULLY`);
    console.log(`${'='.repeat(60)}\n`);

    return result;

  } catch (error) {
    console.error(`\n❌ ========================================`);
    console.error(`❌ ERROR in auto-opening execution`);
    console.error(`❌ ========================================`);
    console.error(`Error:`, error.message);
    console.error(`Stack:`, error.stack);
    console.error(`❌ ========================================\n`);

    // Registrar error en Firestore
    await db.collection('systemLogs').add({
      type: 'auto_opening_error',
      businessId,
      day,
      error: error.message,
      stack: error.stack,
      timestamp: FieldValue.serverTimestamp()
    });

    throw error;
  }
}

/**
 * Cloud Function HTTP callable para ejecutar apertura automática.
 * Puede ser invocada desde el frontend o desde otras Cloud Functions.
 * 
 * Ejemplo de invocación desde frontend:
 * ```javascript
 * const autoOpening = httpsCallable(functions, 'autoOpening');
 * const result = await autoOpening({
 *   businessId: 'abc123',
 *   day: '2025-10-21',
 *   timezone: 'America/Lima'
 * });
 * ```
 */
exports.autoOpening = functions
  .runWith({
    timeoutSeconds: 300, // 5 minutos timeout
    memory: '256MB'
  })
  .https
  .onCall(async (data, context) => {
    console.log(`📞 HTTP Callable invoked: autoOpening`);
    console.log(`   Caller:`, context.auth?.uid || 'unauthenticated');
    console.log(`   Data:`, data);

    // Validar parámetros requeridos
    if (!data.businessId) {
      throw new functions.https.HttpsError(
        'invalid-argument',
        'businessId is required'
      );
    }

    if (!data.day) {
      throw new functions.https.HttpsError(
        'invalid-argument',
        'day is required (format: yyyy-LL-dd)'
      );
    }

    try {
      const result = await executeAutoOpening(data);
      return result;
    } catch (error) {
      console.error(`❌ Error in callable function:`, error);
      throw new functions.https.HttpsError(
        'internal',
        error.message,
        { originalError: error.stack }
      );
    }
  });

/**
 * Exportar función interna para uso desde otras Cloud Functions
 */
exports.executeAutoOpening = executeAutoOpening;
