/* eslint-disable */

/**
 * @file lazyCloseIfNeeded.js
 * @description Función callable que cierra automáticamente TODOS los días pendientes
 * cuando el usuario abre la app. Versión mejorada: cierre en cadena multi-día.
 * 
 * Si el usuario no cerró manualmente durante 3 días, esta función cierra
 * todos esos días en orden cronológico para mantener la continuidad de saldos.
 * 
 * Infraestructura consistente con:
 * - useTransaction.js (manejo de transacciones)
 * - useCashClosure.js (lógica de cierre)
 * - transactionStore.js (estructura de transacciones)
 * 
 * @module AccountsBalance/lazyCloseIfNeeded
 */

// Firebase Functions v1
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const { v4: uuidv4 } = require('uuid');

// Inicializar Firebase Admin si no está inicializado
if (!admin.apps.length) {
  admin.initializeApp();
}

const db = admin.firestore();

const { todayStr, dayMinus, endOfDay } = require('../Helpers/time');
const { getDayAggregates, upsertDailySummary } = require('./sharedComputed');
const { updateStreakContextualizada } = require('../Streak/streakManager');

const DEFAULT_TZ = 'America/Lima';

/**
 * Máximo de días hacia atrás a buscar para cierre en cadena.
 * 30 días es un balance entre cobertura y rendimiento.
 */
const MAX_LOOKBACK_DAYS = 30;

/**
 * Crea una transacción de cierre automático para un día específico.
 * 
 * @param {Object} params
 * @param {string} params.businessId
 * @param {string} params.day - Día a cerrar (yyyy-LL-dd)
 * @param {Object} params.agg - Agregados del día (de getDayAggregates)
 * @param {string} params.tz - Timezone del negocio
 * @returns {Object} { closureUuid, closureTransaction }
 */
async function createClosureForDay({ businessId, day, agg, tz }) {
  const closureUuid = uuidv4();
  const closureRef = db.collection(`businesses/${businessId}/transactions`).doc(closureUuid);

  // Acceso seguro a propiedades anidadas
  const openingData = agg.openingData || {};
  const { byAccount, balances, totals, transfers, adjustments, operational } = agg;

  // Timestamp del final del día (23:59:59.999) para que el cierre pertenezca al día correcto
  const closureTimestamp = admin.firestore.Timestamp.fromDate(endOfDay(day, tz));

  // Estructura completa de cierre (consistente con buildClosureTransaction)
  const closureTransaction = {
    // === IDENTIFICACIÓN ===
    uuid: closureUuid,
    id: closureUuid,
    type: 'closure',
    description: 'Cierre automático (lazy-open)',
    source: 'copilot',
    copilotMode: 'lazyOpen',
    openingReference: openingData.uuid || openingData.id,

    // === SALDOS INICIALES (de apertura) ===
    initialCashBalance: openingData.realCashBalance || 0,
    initialBankBalance: openingData.realBankBalance || 0,

    // === TOTALES GENERALES (sin ajustes) ===
    totalIngresos: totals?.income || 0,
    totalEgresos: totals?.expense || 0,
    ingresosCash: byAccount?.cash?.income || 0,
    ingresosBank: byAccount?.bank?.income || 0,
    egresosCash: byAccount?.cash?.expense || 0,
    egresosBank: byAccount?.bank?.expense || 0,

    // === TRANSFERENCIAS ===
    totalTransferencias: transfers?.total || 0,
    transferencias: {
      cash: {
        in: transfers?.cash?.in || 0,
        out: transfers?.cash?.out || 0,
        net: transfers?.cash?.net || 0
      },
      bank: {
        in: transfers?.bank?.in || 0,
        out: transfers?.bank?.out || 0,
        net: transfers?.bank?.net || 0
      }
    },

    // === AJUSTES ===
    ajustesApertura: {
      cash: adjustments?.opening?.cash || 0,
      bank: adjustments?.opening?.bank || 0,
      total: adjustments?.opening?.total || 0
    },
    ajustesCierre: {
      cash: 0,
      bank: 0,
      total: 0
    },

    // === BALANCES ESPERADOS ===
    expectedCashBalance: balances?.expected?.cash || 0,
    expectedBankBalance: balances?.expected?.bank || 0,

    // === BALANCES REALES (igual a esperados en cierre automático) ===
    realCashBalance: balances?.actual?.cash || 0,
    realBankBalance: balances?.actual?.bank || 0,

    // === DIFERENCIAS (0 en cierre automático sin conteo real) ===
    cashDifference: 0,
    bankDifference: 0,

    // === RESULTADOS OPERACIONALES ===
    resultadoOperacional: operational?.result || 0,
    resultadoOperacionalCash: operational?.resultCash || 0,
    resultadoOperacionalBank: operational?.resultBank || 0,
    flujoNetoCash: operational?.flowCash || 0,
    flujoNetoBank: operational?.flowBank || 0,

    // === CAMPOS COMPATIBLES (legacy) ===
    totalCash: balances?.actual?.cash || 0,
    totalBank: balances?.actual?.bank || 0,
    cashAmount: balances?.actual?.cash || 0,
    bankAmount: balances?.actual?.bank || 0,

    // === ESTRUCTURA ESTÁNDAR ===
    items: [],
    itemsAndStockLogs: [],
    amount: 0,

    // === METADATA ===
    metadata: {
      closedDay: day,
      triggerType: 'lazy_open',
      autoGenerated: true,
      actualExecutionTime: new Date().toISOString(),
      closureTimestamp: closureTimestamp.toDate().toISOString()
    },
    // IMPORTANTE: createdAt debe ser el final del día anterior (23:59:59.999)
    createdAt: closureTimestamp
  };

  // Crear transacción de cierre
  await closureRef.set(closureTransaction);
  console.log(`  ✅ Closure created for ${day}: ${closureUuid}`);

  // Recalcular agregados después del cierre
  const updatedAgg = await getDayAggregates(db, businessId, day, tz);

  // Actualizar resumen diario
  await upsertDailySummary(db, businessId, day, {
    ...updatedAgg,
    hasClosure: true,
    isAutoClosed: true,
    closureId: closureUuid,
    autoCloseReason: 'lazyOpen',
    completedAt: admin.firestore.FieldValue.serverTimestamp()
  });

  // Actualizar racha
  const streakResult = await updateStreakContextualizada({
    db,
    businessId,
    day,
    summary: {
      ...updatedAgg,
      hasClosure: true,
      isAutoClosed: true,
      closureId: closureUuid,
      autoCloseReason: 'lazyOpen'
    },
    tz,
    autoClosePolicy: 'lenient'
  });

  console.log(`  🔥 Streak for ${day}:`, {
    updated: streakResult.updated,
    current: streakResult.streak?.current,
    reason: streakResult.reason
  });

  // Traceability log
  await db.collection(`businesses/${businessId}/traceability_logs`).add({
    operationType: 'auto_close',
    entityType: 'transaction',
    entityId: closureUuid,
    operation: 'lazy_open_closure',
    day,
    closureTransactionId: closureUuid,
    triggerType: 'lazy_open',
    autoGenerated: true,
    financialData: {
      totalIngresos: closureTransaction.totalIngresos,
      totalEgresos: closureTransaction.totalEgresos,
      expectedCashBalance: closureTransaction.expectedCashBalance,
      expectedBankBalance: closureTransaction.expectedBankBalance,
      realCashBalance: closureTransaction.realCashBalance,
      realBankBalance: closureTransaction.realBankBalance
    },
    closureTimestamp: closureTimestamp,
    executedAt: admin.firestore.FieldValue.serverTimestamp(),
    timestamp: admin.firestore.FieldValue.serverTimestamp()
  });

  return { closureUuid, closureTransaction };
}

/**
 * Cierra automáticamente TODOS los días pendientes (multi-día).
 * Busca hasta MAX_LOOKBACK_DAYS hacia atrás y cierra en orden cronológico.
 */
module.exports = functions.https.onCall(async (data, context) => {
  // === VALIDACIÓN DE AUTENTICACIÓN ===
  if (!context.auth || !context.auth.uid) {
    throw new functions.https.HttpsError('unauthenticated', 'Autenticación requerida');
  }

  // === VALIDACIÓN DE PARÁMETROS ===
  const businessId = data && data.businessId;
  if (!businessId) {
    throw new functions.https.HttpsError('invalid-argument', 'businessId es requerido');
  }

  console.log(`🔍 Lazy close check (multi-day) for business: ${businessId}`);

  // === OBTENER TIMEZONE DEL NEGOCIO ===
  const businessDoc = await db.doc(`businesses/${businessId}`).get();

  if (!businessDoc.exists) {
    throw new functions.https.HttpsError('not-found', `Negocio ${businessId} no encontrado`);
  }

  const businessData = businessDoc.data();
  const tz = (businessData && businessData.timezone) || DEFAULT_TZ;

  // === BUSCAR TODOS LOS DÍAS SIN CIERRE (hasta MAX_LOOKBACK_DAYS atrás) ===
  const today = todayStr(tz);
  const pendingDays = []; // Días que necesitan cierre

  console.log(`📅 Searching for unclosed days from today: ${today} (tz: ${tz})`);

  for (let i = 1; i <= MAX_LOOKBACK_DAYS; i++) {
    const checkDay = dayMinus(today, i, tz);

    // Leer dailySummary para este día
    const summaryRef = db.doc(`businesses/${businessId}/dailySummaries/${checkDay}`);
    const summarySnap = await summaryRef.get();

    if (!summarySnap.exists) {
      // No hay dailySummary = no hubo actividad = no necesita cierre
      // Seguir buscando más atrás por si hay días anteriores con apertura
      console.log(`  📅 ${checkDay}: No dailySummary (no activity) - continuing search`);
      continue;
    }

    const summary = summarySnap.data();

    if (summary.hasOpening && !summary.hasClosure) {
      // Día con apertura pero sin cierre → necesita cierre
      console.log(`  ⚠️  ${checkDay}: NEEDS CLOSURE (hasOpening=true, hasClosure=false)`);
      pendingDays.push(checkDay);
    } else if (summary.hasClosure) {
      // Encontramos un día cerrado → ya no necesitamos buscar más atrás
      console.log(`  ✅ ${checkDay}: Already closed - stopping search`);
      break;
    } else {
      // Tiene dailySummary pero no tiene opening (raro, pero posible)
      console.log(`  ℹ️  ${checkDay}: No opening - skipping`);
    }
  }

  // === SI NO HAY DÍAS PENDIENTES ===
  if (pendingDays.length === 0) {
    console.log(`ℹ️  No automatic closure needed`);
    return {
      closed: false,
      reason: 'no_missing_closure',
      today
    };
  }

  // === CERRAR EN ORDEN CRONOLÓGICO (más antiguo primero) ===
  // Esto es crucial: cada cierre alimenta los saldos del día siguiente.
  pendingDays.reverse();
  console.log(`\n🔒 Closing ${pendingDays.length} pending day(s) in order: ${pendingDays.join(', ')}`);

  const closedDays = [];

  for (const day of pendingDays) {
    console.log(`\n📅 Closing day: ${day}`);

    try {
      // Obtener agregados del día
      const agg = await getDayAggregates(db, businessId, day, tz);

      if (!agg.hasOpening) {
        console.log(`  ⚠️  ${day}: Opening disappeared - skipping`);
        continue;
      }

      const { closureUuid } = await createClosureForDay({
        businessId,
        day,
        agg,
        tz
      });

      closedDays.push({
        day,
        closureId: closureUuid
      });

    } catch (dayError) {
      console.error(`  ❌ Error closing day ${day}:`, dayError.message);
      // Continuar con el siguiente día
    }
  }

  // === RESULTADO ===
  if (closedDays.length > 0) {
    console.log(`\n✅ Closed ${closedDays.length} day(s) successfully`);
    return {
      closed: true,
      mode: 'lazyOpen',
      daysCount: closedDays.length,
      closedDays,
      // Retrocompatibilidad: devolver el último día cerrado
      day: closedDays[closedDays.length - 1].day,
      closureId: closedDays[closedDays.length - 1].closureId
    };
  }

  return {
    closed: false,
    reason: 'no_valid_days_to_close',
    today
  };
});
