/* eslint-disable */

/**
 * @file testScheduledAutoClose.js
 * @description Función HTTP para testing del cierre automático programado.
 * Simula el comportamiento del scheduler que cierra días abiertos automáticamente.
 * 
 * Infraestructura consistente con:
 * - useTransaction.js (creación de transacciones)
 * - transactionStore.js (estructura de datos)
 * - useCashClosure.js (lógica de cierre)
 * - accountsBalanceStore.js (cálculos financieros)
 * 
 * @module AccountsBalance/testScheduledAutoClose
 */

const functions = require('firebase-functions');
const admin = require('firebase-admin');
const { FieldValue } = require('firebase-admin/firestore');
const { v4: uuidv4 } = require('uuid');

if (!admin.apps.length) {
  admin.initializeApp();
}

const db = admin.firestore();

const { yesterdayStr } = require('../Helpers/time');
const { getDayAggregates, upsertDailySummary } = require('./sharedComputed');
const { breakStreak, incStreakIfConsecutive } = require('./sharedStreak');

const DEFAULT_TZ = 'America/Lima';

/**
 * Función de testing para el cierre automático programado.
 * Procesa todos los negocios (o uno específico) y cierra días pendientes.
 * 
 * Casos de uso:
 * 1. Día abierto sin cierre → Crea cierre automático
 * 2. Día completo (apertura + transacciones + cierre) → Incrementa racha
 * 3. Día sin apertura o sin actividad → No hace nada
 * 
 * Query params:
 * - businessId (opcional): Procesar solo un negocio específico
 * 
 * Response:
 * - success: boolean
 * - results: Array con el resultado de cada negocio
 * - timestamp: ISO string
 */
module.exports = functions.https.onRequest(async (request, response) => {
  try {
    console.log('🧪 TEST: scheduledAutoClose');
    console.log(`🕐 Started at: ${new Date().toISOString()}`);

    // Permite pasar un businessId específico para testing
    const testBusinessId = request.query.businessId;

    let businesses;
    if (testBusinessId) {
      console.log(`🎯 Testing single business: ${testBusinessId}`);
      const doc = await db.doc(`businesses/${testBusinessId}`).get();

      if (!doc.exists) {
        console.error(`❌ Business ${testBusinessId} not found`);
        return response.status(404).json({
          success: false,
          error: `Negocio ${testBusinessId} no encontrado`
        });
      }

      businesses = { docs: [doc], size: 1 };
    } else {
      console.log(`📊 Testing all businesses`);
      businesses = await db.collection('businesses').get();
      console.log(`📊 Found ${businesses.size} businesses`);
    }

    const results = [];

    // Procesar cada negocio
    for (const b of businesses.docs) {
      if (!b.exists) {
        console.log('⚠️  Document does not exist, skipping...');
        continue;
      }

      const businessId = b.id;
      const businessData = b.data();
      const tz = (businessData && businessData.timezone) || DEFAULT_TZ;

      console.log(`\n${'='.repeat(60)}`);
      console.log(`🏪 Business: ${businessId}`);
      console.log(`🌍 Timezone: ${tz}`);

      // === CALCULAR DÍA ANTERIOR ===
      const day = yesterdayStr(tz);
      console.log(`📅 Processing day: ${day}`);

      // === OBTENER AGREGADOS DEL DÍA ===
      const agg = await getDayAggregates(db, businessId, day, tz);
      console.log(`📊 Aggregates:`, {
        hasOpening: agg.hasOpening,
        hasClosure: agg.hasClosure,
        hasTxn: agg.hasTxn,
        totals: agg.totals,
        operational: agg.operational
      });

      // Actualizar resumen diario con estructura completa
      await upsertDailySummary(db, businessId, day, {
        ...agg // Estructura completa de accountsBalanceStore
      });

      let action = 'none';
      let transactionId = null;

      // === CASO 1: DÍA ABIERTO SIN CIERRE ===
      if (agg.hasOpening && !agg.hasClosure) {
        console.log(`⚠️  OPEN without closure - Creating automatic closure`);

        // Generar UUID para la transacción (consistente con useTransaction)
        const closureUuid = uuidv4();
        const closureRef = db.collection(`businesses/${businessId}/transactions`).doc(closureUuid);

        // Estructura de transacción consistente con transactionStore
        const closureTransaction = {
          uuid: closureUuid,
          type: 'closure',
          description: 'Cierre automático (scheduled)',
          source: 'copilot',
          copilotMode: 'scheduled',
          account: 'cash', // Default account
          amount: 0,
          // Metadata para trazabilidad
          metadata: {
            day: day,
            triggerType: 'scheduled_auto_close',
            autoGenerated: true,
            testMode: true,
            aggregates: {
              totalIncome: agg.totals.income,
              totalExpense: agg.totals.expense,
              netResult: agg.totals.net
            }
          },
          createdAt: FieldValue.serverTimestamp()
        };

        // Crear transacción de cierre
        await closureRef.set(closureTransaction);
        transactionId = closureUuid;
        console.log(`✅ Closure created: ${closureUuid}`);

        // Actualizar resumen diario con info de cierre (merge sobre datos existentes)
        await upsertDailySummary(db, businessId, day, {
          hasClosure: true,
          isAutoClosed: true,
          closureId: closureUuid,
          autoCloseReason: 'test',
          completedAt: FieldValue.serverTimestamp()
        });
        console.log(`✅ Daily summary updated with closure info`);

        // Romper racha
        await breakStreak(db, businessId);
        action = 'auto-closed';
        console.log(`📉 Streak broken`);

      }
      // === CASO 2: DÍA COMPLETO ===
      else if (agg.hasOpening && agg.hasTxn && agg.hasClosure) {
        console.log(`✨ Complete day - Incrementing streak`);
        await incStreakIfConsecutive(db, businessId, day, tz);
        action = 'streak-increased';
        console.log(`📈 Streak incremented`);
      }
      // === CASO 3: SIN ACCIÓN NECESARIA ===
      else {
        console.log(`ℹ️  No action needed`);

        if (!agg.hasOpening) {
          console.log(`   - No opening found`);
        }
        if (!agg.hasTxn) {
          console.log(`   - No transactions found`);
        }
      }

      // Guardar resultado
      results.push({
        businessId,
        day,
        timezone: tz,
        action,
        transactionId,
        aggregates: {
          hasOpening: agg.hasOpening,
          hasClosure: agg.hasClosure,
          hasTransactions: agg.hasTxn,
          totals: agg.totals
        },
        timestamp: new Date().toISOString()
      });
    }

    console.log(`\n${'='.repeat(60)}`);
    console.log('✅ TEST completed successfully');
    console.log(`📊 Processed ${results.length} businesses`);
    console.log(`🕐 Finished at: ${new Date().toISOString()}`);

    // Resumen de acciones
    const summary = {
      total: results.length,
      autoClosed: results.filter(r => r.action === 'auto-closed').length,
      streakIncreased: results.filter(r => r.action === 'streak-increased').length,
      noAction: results.filter(r => r.action === 'none').length
    };

    console.log('📈 Summary:', summary);

    response.json({
      success: true,
      summary,
      results,
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    console.error('❌ Error:', error);
    console.error('Stack:', error.stack);

    response.status(500).json({
      success: false,
      error: error.message,
      stack: error.stack,
      timestamp: new Date().toISOString()
    });
  }
});